Api 0 1
BorodaUA/drf_api pull request #2
Opened 2021-09-13 11:55 UTC by BorodaUA

Hi team, I've managed to refactor "/drivers" endpoint, and add permission for "/users" and "/drivers" endpoints. Please review the changes

2021-09-13 21:11 UTC, tropicoo requested changes
Please change PR title to something better :)

2021-09-13 21:11 UTC, tropicoo commented on usefull_app/user_api/serializers.py
> +        return {'user_id': user}
You are performing here some manipulations and instead of `user_id` return `User` instance.  That's ambiguous data and such things rarely pass code review for production if this isn't some very very specific kostyl.

Also I think there's no point here to introduce temporary `user` variable. It's plain simple logic.
```python
        try:
            return {'user_id': User.objects.get(id=data)}
        except User.DoesNotExist:
            raise  ValidationError(f'User with id {data} does not exists.')
```

2021-09-16 13:31 UTC, BorodaUA commented on usefull_app/user_api/permissions.py
> +            return obj.user_id.id == request.user.id
Fixed with new linter setup.

2021-09-16 13:31 UTC, BorodaUA commented on usefull_app/user_api/serializers.py
> +        Return UserSerializer object user's data
dots added to all docstrings.

2021-09-16 13:33 UTC, BorodaUA commented on usefull_app/user_api/serializers.py
> +             Driver.objects.get(user_id_id=user_id)
This logic completely removed, but  info about ```.exists()``` noted.

2021-09-16 13:33 UTC, BorodaUA commented on usefull_app/user_api/serializers.py
> +    def create(self, validated_data):
@transaction.atomic added to methods create\update.

2021-09-16 13:36 UTC, BorodaUA commented on usefull_app/user_api/views.py
> +    renderer_classes = api_settings.DEFAULT_RENDERER_CLASSES
Fixed with new linter setup.

2021-09-16 13:37 UTC, BorodaUA commented on usefull_app/user_api/permissions.py
> +        else:
Removed in new commits.

2021-09-16 13:37 UTC, BorodaUA commented on usefull_app/user_api/permissions.py
> +        else:
Removed in new commits.

2021-09-16 13:38 UTC, BorodaUA commented on usefull_app/user_api/serializers.py
> +            raise ValidationError(f'Incorrect type. Expected a int but got {type(data).__name__}')
This code removed, but info is noted.

2021-09-16 13:40 UTC, BorodaUA commented on usefull_app/user_api/serializers.py
> +        return {'user_id': user}
Separate field for user removed, now using default serializing solution.

2021-09-16 14:00 UTC, tropicoo approved these changes

2021-09-16 14:07 UTC, closed without merging