User api passengers refactoring 1
BorodaUA/drf_api pull request #4
Opened 2021-09-20 07:15 UTC by BorodaUA

Hi team, please review my changers, I've done some refactoring with "/passengers" endpoint and created another one "passengers/{id}/rate" for passenger's rating.

2021-09-20 10:35 UTC, tropicoo requested changes

2021-09-20 10:35 UTC, tropicoo commented on usefull_app/user_api/models.py
> +    def rating(self):
I think it's better to make this as `property` so you won't use parenthesis (`.rating() -> .rating`) every time.

2021-09-20 10:35 UTC, tropicoo commented on usefull_app/user_api/models.py
> +    passenger = models.ForeignKey(Passenger, on_delete=models.CASCADE)
Please add foreign key arg `related_name='ratings'`.

2021-09-20 10:35 UTC, tropicoo commented on usefull_app/user_api/serializers.py
> +            raise ValidationError(detail={"detail": "Passenger cannot rate himself."})
Please use one type of quotes `'` everywhere.

2021-09-20 10:35 UTC, tropicoo commented on usefull_app/common/constants.py
> +API_VERSION = 1
`API_VERSION_V1 = 1` because you eventually will have `API_VERSION_V2 = 2`.
It can be also basic class:
```python
class APIVersion:
    V1 = 1
    V2 = 2
```

2021-09-20 10:35 UTC, tropicoo commented on usefull_app/user_api/migrations/0014_remove_passenger_rate.py
> +# Generated by Django 3.2.6 on 2021-09-16 19:02
You introduce 5 migrations in one PR. It should one bigger.

2021-09-20 10:35 UTC, tropicoo commented on usefull_app/user_api/views.py
> +        return PassengerRating.objects.filter(passenger=self.kwargs['passenger_pk'])
If you use non-existing user id in `/passengers/{id}/rate` will it return 200 or 404?

2021-09-20 13:54 UTC, BorodaUA commented on usefull_app/user_api/models.py
> +    def rating(self):
@property added to rating in new commit.

2021-09-20 13:55 UTC, BorodaUA commented on usefull_app/user_api/models.py
> +    passenger = models.ForeignKey(Passenger, on_delete=models.CASCADE)
related_name added to FK field in new commit.

2021-09-20 13:55 UTC, BorodaUA commented on usefull_app/common/constants.py
> +API_VERSION = 1
New class based API versioning added in new commit.

2021-09-20 13:56 UTC, BorodaUA commented on usefull_app/user_api/views.py
> +        return PassengerRating.objects.filter(passenger=self.kwargs['passenger_pk'])
Migration files 0010-0015 squashed in one migration file.

2021-09-20 13:56 UTC, BorodaUA commented on usefull_app/user_api/migrations/0014_remove_passenger_rate.py
> +# Generated by Django 3.2.6 on 2021-09-16 19:02
Migration files 0010-0015 squashed in one migration file.

2021-09-22 14:34 UTC, tropicoo requested changes

2021-09-22 14:34 UTC, tropicoo commented on usefull_app/usefull_app/settings.py
> +    'django.middleware.gzip.GZipMiddleware',
Please move it to the top. From Django [documentation](https://docs.djangoproject.com/en/3.2/ref/middleware/#module-django.middleware.gzip):
> This middleware should be placed before any other middleware that need to read or write the response body so that compression happens afterward.

2021-09-22 14:34 UTC, tropicoo commented on usefull_app/user_api/serializers.py
> +        if kwargs_passenger_id != payload_passenger_id:
You probably just need to inject `passenger_pk` in the view into serializer payload. Since you can get requesting user instance from context and then perform that validation, you don't need to add additional key into payload itself on the client side.

2021-09-23 07:45 UTC, BorodaUA commented on usefull_app/usefull_app/settings.py
> +    'django.middleware.gzip.GZipMiddleware',
Middleware moved up

2021-09-23 07:46 UTC, BorodaUA commented on usefull_app/user_api/serializers.py
> +        if kwargs_passenger_id != payload_passenger_id:
passenger_id now added from url params

2021-09-23 13:12 UTC, tropicoo requested changes

2021-09-23 13:12 UTC, tropicoo commented on usefull_app/user_api/serializers.py
> +    def create(self, validated_data: Dict) -> NotImplementedError:
You raise an exception,[ don't return it](https://www.python.org/dev/peps/pep-0484/#exceptions).
Basically you logic _wants_ to return `None`, so typing is `-> None:`

2021-09-23 13:12 UTC, tropicoo commented on usefull_app/user_api/views.py
> +    def get_serializer(self, *args: Tuple, **kwargs: Dict) -> 'PassengerRatingViewSet':
For Python >= 3.9 you need to use regular objects like `tuple` instead of `typing.Tuple`. They are for previous versions of python (generics). 
[PEP](https://www.python.org/dev/peps/pep-0585/#id6): _Importing those from typing is deprecated._

2021-09-23 13:50 UTC, BorodaUA commented on usefull_app/user_api/serializers.py
> +    def create(self, validated_data: Dict) -> NotImplementedError:
Good catch tnx

2021-09-23 13:52 UTC, BorodaUA commented on usefull_app/user_api/views.py
> +    def get_serializer(self, *args: Tuple, **kwargs: Dict) -> 'PassengerRatingViewSet':
Typing updated for python 3.9.6 in new commit

2021-09-23 14:24 UTC, merged