Tests for "/passengers/{id}/rate" endpoint
BorodaUA/drf_api pull request #8
Opened 2021-09-30 07:50 UTC by BorodaUA

Hi team, please review changes that I made. It is basic "smoke" tests for "/passengers/{id}/rate" endpoint.

2021-09-30 10:59 UTC, tropicoo requested changes

2021-09-30 10:59 UTC, tropicoo commented on usefull_app/user_api/tests/test_passengers_rate.py
> +        [ ] no user data added to db
What are those brackets for?

2021-09-30 10:59 UTC, tropicoo commented on usefull_app/common/tests.py
> +        Create and return Passenger, with PassengerRating entries added to return entry.
Please remove comma before with.

2021-09-30 10:59 UTC, tropicoo commented on usefull_app/common/tests.py
> +            rate = PassengerRating.objects.create(**rate_data)
There's no need to create a dict and then unpack it.
```suggestion
            rate = PassengerRating.objects.create(
            user=user,
            passenger=passenger,
            rate=5 if number % 2 == 0 else 1,
            )
```

2021-09-30 10:59 UTC, tropicoo commented on usefull_app/common/tests.py
> +        user_data = {
Same here with dict.

2021-09-30 10:59 UTC, tropicoo commented on usefull_app/user_api/tests/test_passengers_rate.py
> +        self.client = APIClient()
You are doing same initialization in every test class. Just use DRF's `APITestCase` instead of `TransactionTestCase`. API client is already there.

2021-09-30 10:59 UTC, tropicoo commented on usefull_app/user_api/tests/test_passengers_rate.py
> +        url = reverse('passenger-ratings-list', args=[f'{passenger.id}'])
Why `args=[f'{passenger.id}']` and not `args=[passenger.id]`?

2021-09-30 10:59 UTC, tropicoo commented on usefull_app/user_api/tests/test_passengers_rate.py
> +        self.assertEqual(expected_result, response.json())
```suggestion
        self.assertEqual(response.json(), expected_result)
```

2021-09-30 10:59 UTC, tropicoo commented on usefull_app/user_api/tests/test_passengers_rate.py
> +        Test GET /passengers/{id}/rate/{id}
Can you please make docstring descriptions something like _Test that GET /passengers/{id}/rate/{id} returns data for existing users with ratings._

2021-09-30 10:59 UTC, tropicoo commented on usefull_app/user_api/tests/test_passengers_rate.py
> +                f'{passenger.id}',
There's no point of using f-strings here.

2021-09-30 10:59 UTC, tropicoo commented on usefull_app/common/tests.py
> +    def add_random_users_to_db() -> User:
You are adding one user, not many.
```suggestion
    def add_random_user_to_db() -> User:
```

2021-09-30 10:59 UTC, tropicoo commented on usefull_app/user_api/tests/test_passengers_rate.py
> +        # duplicate
Please make comments like here more verbose.
```suggestion
        # Try to rate passenger again with same payload.
```

2021-09-30 10:59 UTC, tropicoo commented on usefull_app/user_api/tests/test_passengers_rate.py
> +        self.client.credentials(HTTP_AUTHORIZATION=f'Token {token.key}')
I think you would want to create a simple test class with test cases specifically to test authentication on your API and here only use `self.client.force_authenticate(user=user)` to bypass real authentication every time in every test case in context of test decomposition.

2021-09-30 11:32 UTC, makarkarman commented on usefull_app/common/tests.py
> +            "phone_number": f"+38{uuid1().int}"[:13],
You could use f"+38{random.randrange(1000000000,9999999999)}"
insted of f"+38{uuid1().int}"[:13]

2021-09-30 13:52 UTC, BorodaUA commented on usefull_app/user_api/tests/test_passengers_rate.py
> +        [ ] no user data added to db
Those are removed in new commit.

2021-09-30 13:52 UTC, BorodaUA commented on usefull_app/common/tests.py
> +        Create and return Passenger, with PassengerRating entries added to return entry.
The comma removed.

2021-09-30 13:53 UTC, BorodaUA commented on usefull_app/common/tests.py
> +            rate = PassengerRating.objects.create(**rate_data)
Changed in new commit.

2021-09-30 13:54 UTC, BorodaUA commented on usefull_app/user_api/tests/test_passengers_rate.py
> +        url = reverse('passenger-ratings-list', args=[f'{passenger.id}'])
f'' strings removed in new commit.

2021-09-30 13:54 UTC, BorodaUA commented on usefull_app/user_api/tests/test_passengers_rate.py
> +        self.assertEqual(expected_result, response.json())
Good catch this was the last of them.

2021-09-30 13:55 UTC, BorodaUA commented on usefull_app/user_api/tests/test_passengers_rate.py
> +        Test GET /passengers/{id}/rate/{id}
Docstrings rewritten in new commit.

2021-09-30 13:56 UTC, BorodaUA commented on usefull_app/common/tests.py
> +    def add_random_users_to_db() -> User:
method name changed in new commit.

2021-09-30 13:56 UTC, BorodaUA commented on usefull_app/user_api/tests/test_passengers_rate.py
> +        # duplicate
More verbose comments added in new commit.

2021-09-30 13:57 UTC, BorodaUA commented on usefull_app/user_api/tests/test_passengers_rate.py
> +        self.client.credentials(HTTP_AUTHORIZATION=f'Token {token.key}')
.force_authenticate method used for authentication in new commit.

2021-09-30 13:57 UTC, BorodaUA commented on usefull_app/common/tests.py
> +            "phone_number": f"+38{uuid1().int}"[:13],
Good idea, randrange used in new commit.

2021-09-30 16:02 UTC, tropicoo requested changes

2021-09-30 16:02 UTC, tropicoo commented on usefull_app/user_api/tests/test_passengers_rate.py
> +                rate.id
When you use such type of code expand please always add a comma to the last item because in other case when you add a new element, your changes will show two line changes: 1). Added new comma to previous element; 2). New element itself.

It's also applicable for imports.

2021-10-01 07:45 UTC, BorodaUA commented on usefull_app/common/tests.py
> +            )
This solution used in new commit, tnx!

2021-10-01 07:46 UTC, BorodaUA commented on usefull_app/common/tests.py
> +            "first_name": "john",
So tempting to copy stuff from postman...fixed in new commit.

2021-10-01 07:46 UTC, BorodaUA commented on usefull_app/user_api/tests/test_passengers_rate.py
> +                rate.id
Comma added to multiline stuff in new commit.

2021-10-01 12:22 UTC, tropicoo approved these changes

2021-10-01 12:25 UTC, merged